site_name: Oscovida Documentation
site_description: TODO
site_url: https://oscovida.github.io

theme:
  name: material
  palette:
    scheme: preference
    language: en

repo_name: oscovida/oscovida
repo_url: https://github.com/oscovida/oscovida
edit_uri: ""

nav:
  - Quick-Start: './quick-start.ipynb'
  - Examples:
    - 'Germany': './examples/germany.ipynb'
  - API Reference:
    - 'Regions': './api/regions.md'
    - 'Statistics': './api/statistics.md'
    - 'Plotting': './api/plotting.md'
  - Contributing: './contributing.md'

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
  - mknotebooks:
        binder: true
        binder_service_name: "gh"
        binder_branch: "master"

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - codehilite
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"
