name: Formatting and Setup.py Checks

on:
  pull_request:
  push:
    branches: [master, feature/package-refactoring]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
